"""empty message

Revision ID: 080a62ac916f
Revises: 38f8afdbd065
Create Date: 2025-07-07 21:50:19.805583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080a62ac916f'
down_revision = '38f8afdbd065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_model', schema=None) as batch_op:
        batch_op.drop_column('status_time')

    # ### end Alembic commands ###
