"""empty message

Revision ID: 38f8afdbd065
Revises: ea65b68c9cd2
Create Date: 2025-07-04 21:26:24.397255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f8afdbd065'
down_revision = 'ea65b68c9cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wifi', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_model', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('wifi')

    # ### end Alembic commands ###
