"""empty message

Revision ID: 9579ef63f256
Revises: 4888d3f13ca0
Create Date: 2025-07-07 22:00:30.792954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9579ef63f256'
down_revision = '4888d3f13ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_model', schema=None) as batch_op:
        batch_op.drop_column('sock')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    with op.batch_alter_table('sms_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sock', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
