"""empty message

Revision ID: e3973fb9a4d7
Revises: 9579ef63f256
Create Date: 2025-07-09 17:31:50.967131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3973fb9a4d7'
down_revision = '9579ef63f256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
